services:
    dolibarr-db:
        image: mariadb:11.4
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

        volumes:
            - ${PATH_HOST}/mysql:/var/lib/mysql

    dolibarr:
        image: dolibarr/dolibarr:latest
        environment:
            DOLI_INIT_DEMO: ${DOLI_INIT_DEMO:-0}
            DOLI_DB_HOST: dolibarr-db
            DOLI_DB_NAME: ${MYSQL_DATABASE}
            DOLI_DB_USER: ${MYSQL_USER}
            DOLI_DB_PASSWORD: ${MYSQL_PASSWORD}
            DOLI_URL_ROOT: "${DOMAIN_URL}"
            DOLI_ADMIN_LOGIN: "${DOLI_ADMIN_LOGIN}"
            DOLI_ADMIN_PASSWORD: "${DOLI_ADMIN_PASSWORD}"
            DOLI_CRON: ${DOLI_CRON:-1}
            DOLI_CRON_KEY: ${DOLI_CRON_KEY}
            DOLI_COMPANY_NAME: ${DOLI_COMPANY_NAME}
            WWW_USER_ID: ${WWW_USER_ID:-1000}
            WWW_GROUP_ID: ${WWW_GROUP_ID:-1000}

        ports:
            - ${PORT}:80
        depends_on:
            - dolibarr-db
        volumes:
            - ${PATH_HOST}/documents:/var/www/html/documents
            - ${PATH_HOST}/custom:/var/www/html/custom
