services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - ${PORT}:80
            # - 8443:443 # don't need this if we use reverse proxy
        environment:
            - PUID=${PUID:-1000}
            - PGID=${PGID:-1000}
            - APP_KEY=${APP_KEY}
            - APP_URL=${APP_URL}
            - DB_CONNECTION=sqlite
            - SPEEDTEST_SCHEDULE=${SCHEDULE}
        volumes:
            - ${PATH_HOST_DATA}/config:/config
            # - /path/to-custom-ssl-keys:/config/keys             
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
