services:
  # Minio File Object Store
  minio:
    image: minio/minio:${MINIO_VERSION}
    # image: minio/minio:latest
    container_name: db-minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT_API}:9000" # API
      - "${MINIO_PORT_CONSOLE}:9001" # Console
    volumes:
      - ${MINIO_HOST_PATH}:/data
    command: server /data --console-address ":9001"

  # Redis Caching service, improves performance by storing frequently accessed data
  redis:
    image: redis:${REDIS_VERSION}
    container_name: db-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_HOST_PATH}:/data
    environment:
      - REDIS_PORT=${REDIS_PORT}
    command: > 
      redis-server
      --maxmemory ${REDIS_MAX_MEMORY}
      --maxmemory-policy ${REDIS_EVICTION_POLICY}
    # --user default off
    # --user admin on >${REDIS_ADMIN_PASSWORD} allcommands allkeys

  # Timeseries Column-oriented database (with compression)
  clickhouse:
    image: clickhouse:${CLICKHOUSE_VERSION}
    # image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION} # deprecated
    container_name: db-clickhouse
    restart: unless-stopped
    ports:
      - "${CLICKHOUSE_PORT_HTTP}:8123"  # HTTP interface
      - "${CLICKHOUSE_PORT_TCP}:9000"  # TCP Native client
      - "${CLICKHOUSE_PORT_TLS}:9440"  # TCP Secure Native client
    environment:
      CLICKHOUSE_DB: "forexter"
      
      CLICKHOUSE_USER: ${CLICKHOUSE_ADMIN_USERNAME}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_ADMIN_PASSWORD}

      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_SKIP_USER_SETUP: "0"
    volumes:
      - ${CLICKHOUSE_HOST_PATH}:/var/lib/clickhouse
      - ./docker/clickhouse/config-custom.xml:/etc/clickhouse-server/config.d/zz-config-custom.xml:ro
      - ./docker/clickhouse/users-custom.xml:/etc/clickhouse-server/users.d/zz-users-custom.xml:ro
      - ./docker/clickhouse/cert/server.crt:/etc/clickhouse-server/cert/server.crt:ro
      - ./docker/clickhouse/cert/server.key:/etc/clickhouse-server/cert/server.key:ro

  # Clickhouse Web UI
  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: db-tabix
    ports:
      - "${CLICKHOUSE_TABIX_PORT}:80"  # Tabix UI
    depends_on:
      - clickhouse

  # Postgres Database
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST_PATH: ${POSTGRES_HOST_PATH}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_HOST_PATH}:/var/lib/postgresql/data

  # Postgres Web UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: db-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_PORT: ${PGADMIN_PORT}
      PGADMIN_HOST_PATH: ${PGADMIN_HOST_PATH}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ${PGADMIN_HOST_PATH}:/var/lib/pgadmin
    depends_on:
      - postgres
