# DNS Server
services:
  adguardhome:
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp # plain dns over tcp
      - 53:53/udp # plain dns over udp
      - 80:80/tcp # http web interface
      - 3000:3000/tcp # initial setup web interface
    volumes:
      - ${ADGUARD_HOST_PATH}/conf:/opt/adguardhome/conf # app configuration
      - ${ADGUARD_HOST_PATH}/work:/opt/adguardhome/work # app working directory
