services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    restart: unless-stopped
    environment:
      - HBOX_LOG_LEVEL=error
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=${HBOX_WEB_MAX_UPLOAD_SIZE}
      - HBOX_OPTIONS_ALLOW_ANALYTICS=false
      - HBOX_AUTH_API_KEY_PEPPER=${HBOX_AUTH_API_KEY_PEPPER}
      - HBOX_OPTIONS_ALLOW_REGISTRATION=${HBOX_OPTIONS_ALLOW_REGISTRATION}
    volumes:
      - ${HOMEBOX_DATA_DIR}:/data
    ports:
      - ${HOMEBOX_HOST_PORT}:7745
